name : First Workflow

on : push

jobs: 
  my-frist-ci: 
    name: "First Job"
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Checkout code"
        uses: actions/checkout@v2
      -
        name: "Test Code"
        run: | 
            pip install -r requirements.txt