name: CI CD Workflow

on: push

jobs: 
  Python-CI-Job:
            name: Python-CI-CD-Job
            runs-on: ubuntu-latest
            steps:
                - name: Checkout Codes
                  uses: actions/checkout@v3
                - name: Install Dependencies
                  run: pip install -r requirements.txt 
                - name: Test Code
                  run: pytest
                - name: Build program
                  run: pyinstaller main.py
                - name: List file in dir
                  run: ls -l
                - name: Upload file
                  uses: actions/upload-artifact@v3
                  with:
                     name: program
                     path: dist/* 