name: CI Workflow

on: push

jobs: 
  Python-CI-Job:
            name: Python-CI-Job
            runs-on: ubuntu-latest
            steps:
                - name: Checkout Codes
                  uses: actions/checkout@v3
                - name: Install Dependencies
                  run: pipinstall -r requirements.txt 
                - name: Test Code
                  run: pytest