name: CI Workflow

on: push

jobs: 
  Python-CI-Job:
            name: Python-CI-Job
            runs-on: ubuntu-latest
            steps:
                - name: Checkout Codes
                  uses: actions/checkout@v3
                - name: Install Dependencies
                  run: pip install -r requirements.txt 
                - name: Test Code
                  run: pytest
                - name: Build program
                  run: pyinstaller main.py
                - name : Print dir
                  run: pwd